apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: auth-ns
data:
  ALGORITHM: "HS256"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "rushilshah88@gmail.com"
  EMAIL_FROM_NAME: "Auth Service"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_SECONDS: "40"
  JWT_REFRESH_TOKEN_RENEW_THRESHOLD_SECONDS: "30"
  JWT_REFRESH_TOKEN_EXPIRE_SECONDS: "80"
  GOOGLE_REDIRECT_URI: "http://auth.server.com/api/auth/socials/google/callback"
  GITHUB_REDIRECT_URI: "http://auth.server.com/api/auth/socials/github/callback"
  # URLs will be set based on environment
  SERVER_BASE_URL: "http://auth.server.com"
  CLIENT_BASE_URL: "http://auth.client:3000"