apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SERVER_BASE_URL: "https://auth.yourdomain.com"
  CLIENT_BASE_URL: "https://yourdomain.com"
  GOOGLE_REDIRECT_URI: "https://auth.yourdomain.com/api/auth/socials/google/callback"
  GITHUB_REDIRECT_URI: "https://auth.yourdomain.com/api/auth/socials/github/callback"
  JWT_ACCESS_TOKEN_EXPIRE_SECONDS: "1800"
  JWT_REFRESH_TOKEN_EXPIRE_SECONDS: "2592000"