apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: auth-ns
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # 👈 Important for StatefulSet (headless service)
  selector:
    app: postgres