apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SERVER_BASE_URL: "http://auth-service.auth-service.svc.cluster.local:8000"
  CLIENT_BASE_URL: "http://localhost:3000"
  GOOGLE_REDIRECT_URI: "http://auth-service.auth-service.svc.cluster.local:8000/api/auth/socials/google/callback"
  GITHUB_REDIRECT_URI: "http://auth-service.auth-service.svc.cluster.local:8000/api/auth/socials/github/callback"
  JWT_ACCESS_TOKEN_EXPIRE_SECONDS: "900"
  JWT_REFRESH_TOKEN_EXPIRE_SECONDS: "2592000"