apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth-service

resources:
  - ../../base
  - ../../postgres
  - ../../auth-service
  - ../../networking

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml

images:
  - name: rushilshah23/auth-api
    newTag: dev-latest